"""add_analysis_aggregates_and_focus_tables

Revision ID: 4c84fc4d3e07
Revises: e5cdde793268
Create Date: 2025-10-18 13:31:23.240529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c84fc4d3e07'
down_revision = 'e5cdde793268'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agg_adgroup_daily',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=100), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('ad_group_id', sa.String(length=100), nullable=False),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conversions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('conversions_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cvr', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'ad_group_id', 'date', name='uq_agg_adgroup_daily')
    )
    op.create_index('idx_agg_adgroup_date', 'agg_adgroup_daily', ['client_id', 'date'], unique=False)
    op.create_index('idx_agg_adgroup_perf', 'agg_adgroup_daily', ['client_id', 'cpa', 'roas'], unique=False)
    op.create_index(op.f('ix_agg_adgroup_daily_ad_group_id'), 'agg_adgroup_daily', ['ad_group_id'], unique=False)
    op.create_index(op.f('ix_agg_adgroup_daily_campaign_id'), 'agg_adgroup_daily', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_agg_adgroup_daily_client_id'), 'agg_adgroup_daily', ['client_id'], unique=False)
    op.create_index(op.f('ix_agg_adgroup_daily_date'), 'agg_adgroup_daily', ['date'], unique=False)
    op.create_index(op.f('ix_agg_adgroup_daily_id'), 'agg_adgroup_daily', ['id'], unique=False)
    op.create_table('agg_campaign_daily',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=100), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conversions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('conversions_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cvr', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'campaign_id', 'date', name='uq_agg_campaign_daily')
    )
    op.create_index('idx_agg_campaign_date', 'agg_campaign_daily', ['client_id', 'date'], unique=False)
    op.create_index('idx_agg_campaign_perf', 'agg_campaign_daily', ['client_id', 'cpa', 'roas'], unique=False)
    op.create_index(op.f('ix_agg_campaign_daily_campaign_id'), 'agg_campaign_daily', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_agg_campaign_daily_client_id'), 'agg_campaign_daily', ['client_id'], unique=False)
    op.create_index(op.f('ix_agg_campaign_daily_date'), 'agg_campaign_daily', ['date'], unique=False)
    op.create_index(op.f('ix_agg_campaign_daily_id'), 'agg_campaign_daily', ['id'], unique=False)
    op.create_table('agg_keyword_daily',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=100), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('ad_group_id', sa.String(length=100), nullable=False),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('keyword_id', sa.String(length=100), nullable=False),
    sa.Column('keyword_text', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conversions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('conversions_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cvr', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'keyword_id', 'date', name='uq_agg_keyword_daily')
    )
    op.create_index('idx_agg_keyword_date', 'agg_keyword_daily', ['client_id', 'date'], unique=False)
    op.create_index('idx_agg_keyword_perf', 'agg_keyword_daily', ['client_id', 'cpa', 'quality_score'], unique=False)
    op.create_index('idx_agg_keyword_text', 'agg_keyword_daily', ['client_id', 'keyword_text'], unique=False)
    op.create_index(op.f('ix_agg_keyword_daily_client_id'), 'agg_keyword_daily', ['client_id'], unique=False)
    op.create_index(op.f('ix_agg_keyword_daily_date'), 'agg_keyword_daily', ['date'], unique=False)
    op.create_index(op.f('ix_agg_keyword_daily_id'), 'agg_keyword_daily', ['id'], unique=False)
    op.create_index(op.f('ix_agg_keyword_daily_keyword_id'), 'agg_keyword_daily', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_agg_keyword_daily_keyword_text'), 'agg_keyword_daily', ['keyword_text'], unique=False)
    op.create_table('agg_search_term_daily',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=100), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('ad_group_id', sa.String(length=100), nullable=False),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('search_term', sa.String(length=500), nullable=False),
    sa.Column('match_type_delivered', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conversions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('conversions_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cvr', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'search_term', 'date', name='uq_agg_search_term_daily')
    )
    op.create_index('idx_agg_search_term_date', 'agg_search_term_daily', ['client_id', 'date'], unique=False)
    op.create_index('idx_agg_search_term_perf', 'agg_search_term_daily', ['client_id', 'cost', 'conversions'], unique=False)
    op.create_index('idx_agg_search_term_text', 'agg_search_term_daily', ['client_id', 'search_term'], unique=False)
    op.create_index(op.f('ix_agg_search_term_daily_client_id'), 'agg_search_term_daily', ['client_id'], unique=False)
    op.create_index(op.f('ix_agg_search_term_daily_date'), 'agg_search_term_daily', ['date'], unique=False)
    op.create_index(op.f('ix_agg_search_term_daily_id'), 'agg_search_term_daily', ['id'], unique=False)
    op.create_index(op.f('ix_agg_search_term_daily_search_term'), 'agg_search_term_daily', ['search_term'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('feature_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'ERROR', name='analysisrunstatus'), nullable=False),
    sa.Column('current_phase', sa.Enum('PREPARE', 'KEYWORDS', 'BIDDING', 'SYNTHESIS', 'PERSIST', name='analysisrunphase'), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_cache', 'analysis_runs', ['client_id', 'feature_hash', 'prompt_version', 'created_at'], unique=False)
    op.create_index('idx_analysis_status', 'analysis_runs', ['client_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_analysis_runs_client_id'), 'analysis_runs', ['client_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_feature_hash'), 'analysis_runs', ['feature_hash'], unique=False)
    op.create_index(op.f('ix_analysis_runs_id'), 'analysis_runs', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_run_id'), 'analysis_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_analysis_runs_status'), 'analysis_runs', ['status'], unique=False)
    op.create_table('client_targets',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('target_cpa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_roas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('daily_budget_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpa_alert_threshold_pct', sa.Float(), nullable=False),
    sa.Column('roas_alert_threshold_pct', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_targets_client_id'), 'client_targets', ['client_id'], unique=True)
    op.create_index(op.f('ix_client_targets_id'), 'client_targets', ['id'], unique=False)
    op.create_table('analysis_recommendations',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('COST_EFFICIENCY', 'QUERY_HYGIENE', 'BIDDING', 'BUDGET', 'GEO', 'DEVICE', 'DEMO', name='recommendationcategory'), nullable=False),
    sa.Column('action', sa.Enum('ADD_NEGATIVE', 'PAUSE_KEYWORD', 'CHANGE_BID', 'SHIFT_BUDGET', 'CREATE_PARALLEL_CAMPAIGN', name='recommendationaction'), nullable=False),
    sa.Column('rationale_md', sa.Text(), nullable=False),
    sa.Column('expected_impact', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('prerequisites', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendation_category', 'analysis_recommendations', ['category', 'action'], unique=False)
    op.create_index('idx_recommendation_risk', 'analysis_recommendations', ['risk', 'confidence'], unique=False)
    op.create_index(op.f('ix_analysis_recommendations_action'), 'analysis_recommendations', ['action'], unique=False)
    op.create_index(op.f('ix_analysis_recommendations_category'), 'analysis_recommendations', ['category'], unique=False)
    op.create_index(op.f('ix_analysis_recommendations_id'), 'analysis_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_recommendations_run_id'), 'analysis_recommendations', ['run_id'], unique=False)
    op.create_table('analysis_reports',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('top_issues_count', sa.Integer(), nullable=True),
    sa.Column('recommendations_count', sa.Integer(), nullable=True),
    sa.Column('has_parallel_campaign', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_health', 'analysis_reports', ['health_score', 'created_at'], unique=False)
    op.create_index(op.f('ix_analysis_reports_id'), 'analysis_reports', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_reports_run_id'), 'analysis_reports', ['run_id'], unique=True)
    op.create_table('recommendation_decisions',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'MODIFIED', name='decisionstatus'), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('modified_values', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['analysis_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_decisions_decision'), 'recommendation_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_recommendation_decisions_id'), 'recommendation_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_decisions_recommendation_id'), 'recommendation_decisions', ['recommendation_id'], unique=True)
    op.create_table('action_executions',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'ROLLED_BACK', name='actionstatus'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_by', sa.Integer(), nullable=True),
    sa.Column('api_request', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('api_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('api_error', sa.Text(), nullable=True),
    sa.Column('rollback_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['recommendation_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_status', 'action_executions', ['status', 'executed_at'], unique=False)
    op.create_index(op.f('ix_action_executions_decision_id'), 'action_executions', ['decision_id'], unique=True)
    op.create_index(op.f('ix_action_executions_id'), 'action_executions', ['id'], unique=False)
    op.create_index(op.f('ix_action_executions_status'), 'action_executions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_executions_status'), table_name='action_executions')
    op.drop_index(op.f('ix_action_executions_id'), table_name='action_executions')
    op.drop_index(op.f('ix_action_executions_decision_id'), table_name='action_executions')
    op.drop_index('idx_action_status', table_name='action_executions')
    op.drop_table('action_executions')
    op.drop_index(op.f('ix_recommendation_decisions_recommendation_id'), table_name='recommendation_decisions')
    op.drop_index(op.f('ix_recommendation_decisions_id'), table_name='recommendation_decisions')
    op.drop_index(op.f('ix_recommendation_decisions_decision'), table_name='recommendation_decisions')
    op.drop_table('recommendation_decisions')
    op.drop_index(op.f('ix_analysis_reports_run_id'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_id'), table_name='analysis_reports')
    op.drop_index('idx_report_health', table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_analysis_recommendations_run_id'), table_name='analysis_recommendations')
    op.drop_index(op.f('ix_analysis_recommendations_id'), table_name='analysis_recommendations')
    op.drop_index(op.f('ix_analysis_recommendations_category'), table_name='analysis_recommendations')
    op.drop_index(op.f('ix_analysis_recommendations_action'), table_name='analysis_recommendations')
    op.drop_index('idx_recommendation_risk', table_name='analysis_recommendations')
    op.drop_index('idx_recommendation_category', table_name='analysis_recommendations')
    op.drop_table('analysis_recommendations')
    op.drop_index(op.f('ix_client_targets_id'), table_name='client_targets')
    op.drop_index(op.f('ix_client_targets_client_id'), table_name='client_targets')
    op.drop_table('client_targets')
    op.drop_index(op.f('ix_analysis_runs_status'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_run_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_feature_hash'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_client_id'), table_name='analysis_runs')
    op.drop_index('idx_analysis_status', table_name='analysis_runs')
    op.drop_index('idx_analysis_cache', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_agg_search_term_daily_search_term'), table_name='agg_search_term_daily')
    op.drop_index(op.f('ix_agg_search_term_daily_id'), table_name='agg_search_term_daily')
    op.drop_index(op.f('ix_agg_search_term_daily_date'), table_name='agg_search_term_daily')
    op.drop_index(op.f('ix_agg_search_term_daily_client_id'), table_name='agg_search_term_daily')
    op.drop_index('idx_agg_search_term_text', table_name='agg_search_term_daily')
    op.drop_index('idx_agg_search_term_perf', table_name='agg_search_term_daily')
    op.drop_index('idx_agg_search_term_date', table_name='agg_search_term_daily')
    op.drop_table('agg_search_term_daily')
    op.drop_index(op.f('ix_agg_keyword_daily_keyword_text'), table_name='agg_keyword_daily')
    op.drop_index(op.f('ix_agg_keyword_daily_keyword_id'), table_name='agg_keyword_daily')
    op.drop_index(op.f('ix_agg_keyword_daily_id'), table_name='agg_keyword_daily')
    op.drop_index(op.f('ix_agg_keyword_daily_date'), table_name='agg_keyword_daily')
    op.drop_index(op.f('ix_agg_keyword_daily_client_id'), table_name='agg_keyword_daily')
    op.drop_index('idx_agg_keyword_text', table_name='agg_keyword_daily')
    op.drop_index('idx_agg_keyword_perf', table_name='agg_keyword_daily')
    op.drop_index('idx_agg_keyword_date', table_name='agg_keyword_daily')
    op.drop_table('agg_keyword_daily')
    op.drop_index(op.f('ix_agg_campaign_daily_id'), table_name='agg_campaign_daily')
    op.drop_index(op.f('ix_agg_campaign_daily_date'), table_name='agg_campaign_daily')
    op.drop_index(op.f('ix_agg_campaign_daily_client_id'), table_name='agg_campaign_daily')
    op.drop_index(op.f('ix_agg_campaign_daily_campaign_id'), table_name='agg_campaign_daily')
    op.drop_index('idx_agg_campaign_perf', table_name='agg_campaign_daily')
    op.drop_index('idx_agg_campaign_date', table_name='agg_campaign_daily')
    op.drop_table('agg_campaign_daily')
    op.drop_index(op.f('ix_agg_adgroup_daily_id'), table_name='agg_adgroup_daily')
    op.drop_index(op.f('ix_agg_adgroup_daily_date'), table_name='agg_adgroup_daily')
    op.drop_index(op.f('ix_agg_adgroup_daily_client_id'), table_name='agg_adgroup_daily')
    op.drop_index(op.f('ix_agg_adgroup_daily_campaign_id'), table_name='agg_adgroup_daily')
    op.drop_index(op.f('ix_agg_adgroup_daily_ad_group_id'), table_name='agg_adgroup_daily')
    op.drop_index('idx_agg_adgroup_perf', table_name='agg_adgroup_daily')
    op.drop_index('idx_agg_adgroup_date', table_name='agg_adgroup_daily')
    op.drop_table('agg_adgroup_daily')
    # ### end Alembic commands ###

