"""Initial schema - 17 tables

Revision ID: ccad2446c1e9
Revises: 
Create Date: 2025-10-18 05:49:07.742695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccad2446c1e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', name='clientstatus'), nullable=False),
    sa.Column('google_ads_customer_id', sa.String(length=50), nullable=True),
    sa.Column('google_ads_account_name', sa.String(length=255), nullable=True),
    sa.Column('ghl_location_id', sa.String(length=100), nullable=True),
    sa.Column('ghl_contact_id', sa.String(length=100), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_analysis_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_ghl_contact_id'), 'clients', ['ghl_contact_id'], unique=False)
    op.create_index(op.f('ix_clients_ghl_location_id'), 'clients', ['ghl_location_id'], unique=False)
    op.create_index(op.f('ix_clients_google_ads_customer_id'), 'clients', ['google_ads_customer_id'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_slug'), 'clients', ['slug'], unique=True)
    op.create_index(op.f('ix_clients_status'), 'clients', ['status'], unique=False)
    op.create_table('analyses',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date_range_start', sa.Date(), nullable=False),
    sa.Column('date_range_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('analysis_data', sa.JSON(), nullable=True),
    sa.Column('consensus_similarity_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('required_debate', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_client_id'), 'analyses', ['client_id'], unique=False)
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_table('google_ads_ad_groups',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=False),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ad_group_status', sa.String(length=50), nullable=True),
    sa.Column('ad_group_type', sa.String(length=50), nullable=True),
    sa.Column('cpc_bid', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('conversions_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_cpc', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cvr', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'ad_group_id', 'date', name='uq_ad_group_date')
    )
    op.create_index('idx_ad_groups_client_date', 'google_ads_ad_groups', ['client_id', 'date'], unique=False)
    op.create_index(op.f('ix_google_ads_ad_groups_ad_group_id'), 'google_ads_ad_groups', ['ad_group_id'], unique=False)
    op.create_index(op.f('ix_google_ads_ad_groups_campaign_id'), 'google_ads_ad_groups', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_google_ads_ad_groups_client_id'), 'google_ads_ad_groups', ['client_id'], unique=False)
    op.create_index(op.f('ix_google_ads_ad_groups_date'), 'google_ads_ad_groups', ['date'], unique=False)
    op.create_index(op.f('ix_google_ads_ad_groups_id'), 'google_ads_ad_groups', ['id'], unique=False)
    op.create_table('google_ads_campaigns',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_status', sa.String(length=50), nullable=True),
    sa.Column('channel_type', sa.String(length=50), nullable=True),
    sa.Column('bidding_strategy', sa.String(length=50), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('conversions_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('all_conversions', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('view_through_conversions', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_cpc', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_cpm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('impression_share', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('budget_lost_is', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rank_lost_is', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('roas', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'campaign_id', 'date', name='uq_campaign_date')
    )
    op.create_index('idx_campaigns_campaign_id', 'google_ads_campaigns', ['campaign_id'], unique=False)
    op.create_index('idx_campaigns_client_date', 'google_ads_campaigns', ['client_id', 'date'], unique=False)
    op.create_index(op.f('ix_google_ads_campaigns_campaign_id'), 'google_ads_campaigns', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_google_ads_campaigns_client_id'), 'google_ads_campaigns', ['client_id'], unique=False)
    op.create_index(op.f('ix_google_ads_campaigns_date'), 'google_ads_campaigns', ['date'], unique=False)
    op.create_index(op.f('ix_google_ads_campaigns_id'), 'google_ads_campaigns', ['id'], unique=False)
    op.create_table('google_ads_keywords',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=False),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('keyword_text', sa.String(length=500), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=True),
    sa.Column('keyword_status', sa.String(length=50), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('creative_quality', sa.String(length=50), nullable=True),
    sa.Column('landing_page_quality', sa.String(length=50), nullable=True),
    sa.Column('expected_ctr', sa.String(length=50), nullable=True),
    sa.Column('max_cpc_bid', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('final_url', sa.String(length=1000), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('conversions_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_cpc', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cvr', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'keyword_id', 'date', name='uq_keyword_date')
    )
    op.create_index('idx_keywords_client_date', 'google_ads_keywords', ['client_id', 'date'], unique=False)
    op.create_index('idx_keywords_quality_score', 'google_ads_keywords', ['quality_score'], unique=False)
    op.create_index(op.f('ix_google_ads_keywords_client_id'), 'google_ads_keywords', ['client_id'], unique=False)
    op.create_index(op.f('ix_google_ads_keywords_date'), 'google_ads_keywords', ['date'], unique=False)
    op.create_index(op.f('ix_google_ads_keywords_id'), 'google_ads_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_google_ads_keywords_keyword_id'), 'google_ads_keywords', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_google_ads_keywords_keyword_text'), 'google_ads_keywords', ['keyword_text'], unique=False)
    op.create_table('google_ads_search_terms',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=False),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('search_term', sa.String(length=500), nullable=False),
    sa.Column('search_term_status', sa.String(length=50), nullable=True),
    sa.Column('match_type_delivered', sa.String(length=50), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('conversions_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cvr', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_terms_client_date', 'google_ads_search_terms', ['client_id', 'date'], unique=False)
    op.create_index('idx_search_terms_search_term', 'google_ads_search_terms', ['search_term'], unique=False)
    op.create_index('idx_search_terms_zero_conv', 'google_ads_search_terms', ['conversions', 'cost'], unique=False)
    op.create_index(op.f('ix_google_ads_search_terms_client_id'), 'google_ads_search_terms', ['client_id'], unique=False)
    op.create_index(op.f('ix_google_ads_search_terms_date'), 'google_ads_search_terms', ['date'], unique=False)
    op.create_index(op.f('ix_google_ads_search_terms_id'), 'google_ads_search_terms', ['id'], unique=False)
    op.create_index(op.f('ix_google_ads_search_terms_search_term'), 'google_ads_search_terms', ['search_term'], unique=False)
    op.create_table('lsa_leads',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=False),
    sa.Column('charged', sa.Boolean(), nullable=False),
    sa.Column('charge_status', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'BOOKED', 'COMPLETED', 'CANCELLED', name='lsaleadstatus'), nullable=False),
    sa.Column('survey_sent_google', sa.Boolean(), nullable=False),
    sa.Column('survey_sent_internal', sa.Boolean(), nullable=False),
    sa.Column('survey_sent_at', sa.DateTime(), nullable=True),
    sa.Column('survey_response_received', sa.Boolean(), nullable=False),
    sa.Column('survey_rating', sa.Integer(), nullable=True),
    sa.Column('lead_data', sa.JSON(), nullable=True),
    sa.Column('service_category', sa.String(length=100), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lsa_leads_charged'), 'lsa_leads', ['charged'], unique=False)
    op.create_index(op.f('ix_lsa_leads_client_id'), 'lsa_leads', ['client_id'], unique=False)
    op.create_index(op.f('ix_lsa_leads_id'), 'lsa_leads', ['id'], unique=False)
    op.create_index(op.f('ix_lsa_leads_lead_id'), 'lsa_leads', ['lead_id'], unique=True)
    op.create_index(op.f('ix_lsa_leads_status'), 'lsa_leads', ['status'], unique=False)
    op.create_table('lsa_metrics',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_leads', sa.Integer(), nullable=True),
    sa.Column('charged_leads', sa.Integer(), nullable=True),
    sa.Column('uncharged_leads', sa.Integer(), nullable=True),
    sa.Column('surveys_sent', sa.Integer(), nullable=True),
    sa.Column('surveys_responded', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Integer(), nullable=True),
    sa.Column('leads_new', sa.Integer(), nullable=True),
    sa.Column('leads_contacted', sa.Integer(), nullable=True),
    sa.Column('leads_booked', sa.Integer(), nullable=True),
    sa.Column('leads_completed', sa.Integer(), nullable=True),
    sa.Column('leads_cancelled', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lsa_metrics_client_id'), 'lsa_metrics', ['client_id'], unique=False)
    op.create_index(op.f('ix_lsa_metrics_date'), 'lsa_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_lsa_metrics_id'), 'lsa_metrics', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'CLIENT', name='userrole'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('ghl_user_id', sa.String(length=100), nullable=True),
    sa.Column('ghl_location_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_client_id'), 'users', ['client_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_ghl_user_id'), 'users', ['ghl_user_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('ai_consensus_sessions',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('agent_1_output', sa.JSON(), nullable=True),
    sa.Column('agent_2_output', sa.JSON(), nullable=True),
    sa.Column('agent_3_output', sa.JSON(), nullable=True),
    sa.Column('similarity_score_1_2', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('required_debate', sa.Integer(), nullable=True),
    sa.Column('debate_rounds', sa.Integer(), nullable=True),
    sa.Column('final_consensus', sa.JSON(), nullable=True),
    sa.Column('agent_1_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('agent_2_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('agent_3_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_consensus_sessions_analysis_id'), 'ai_consensus_sessions', ['analysis_id'], unique=True)
    op.create_index(op.f('ix_ai_consensus_sessions_id'), 'ai_consensus_sessions', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_id'), 'audit_log', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_type'), 'audit_log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('ghl_access_token', sa.Text(), nullable=True),
    sa.Column('ghl_refresh_token', sa.Text(), nullable=True),
    sa.Column('ghl_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_id'), 'auth_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('campaign_modifications',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('ADD_NEGATIVE_KEYWORD', 'ADD_KEYWORD', 'PAUSE_KEYWORD', 'ENABLE_KEYWORD', 'ADJUST_BUDGET', 'ADJUST_BID', 'UPDATE_AD_COPY', 'CREATE_PARALLEL_CAMPAIGN', 'TRANSITION_BUDGET', 'PAUSE_OLD_CAMPAIGN', name='modificationactiontype'), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('change_data', sa.JSON(), nullable=False),
    sa.Column('ai_confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='modificationpriority'), nullable=False),
    sa.Column('estimated_monthly_impact', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_cpa_improvement', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'APPLIED', 'FAILED', name='modificationstatus'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('applied_by', sa.Integer(), nullable=True),
    sa.Column('api_response', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_modifications_priority', 'campaign_modifications', ['priority', 'status'], unique=False)
    op.create_index('idx_modifications_status_client', 'campaign_modifications', ['status', 'client_id'], unique=False)
    op.create_index(op.f('ix_campaign_modifications_action_type'), 'campaign_modifications', ['action_type'], unique=False)
    op.create_index(op.f('ix_campaign_modifications_analysis_id'), 'campaign_modifications', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_campaign_modifications_client_id'), 'campaign_modifications', ['client_id'], unique=False)
    op.create_index(op.f('ix_campaign_modifications_id'), 'campaign_modifications', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_modifications_priority'), 'campaign_modifications', ['priority'], unique=False)
    op.create_index(op.f('ix_campaign_modifications_status'), 'campaign_modifications', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_modifications_target_id'), 'campaign_modifications', ['target_id'], unique=False)
    op.create_table('lsa_survey_attempts',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('api_response', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lsa_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lsa_survey_attempts_id'), 'lsa_survey_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_lsa_survey_attempts_lead_id'), 'lsa_survey_attempts', ['lead_id'], unique=False)
    op.create_table('reports',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('ghl_file_id', sa.String(length=100), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_analysis_id'), 'reports', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_reports_client_id'), 'reports', ['client_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_client_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_analysis_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_lsa_survey_attempts_lead_id'), table_name='lsa_survey_attempts')
    op.drop_index(op.f('ix_lsa_survey_attempts_id'), table_name='lsa_survey_attempts')
    op.drop_table('lsa_survey_attempts')
    op.drop_index(op.f('ix_campaign_modifications_target_id'), table_name='campaign_modifications')
    op.drop_index(op.f('ix_campaign_modifications_status'), table_name='campaign_modifications')
    op.drop_index(op.f('ix_campaign_modifications_priority'), table_name='campaign_modifications')
    op.drop_index(op.f('ix_campaign_modifications_id'), table_name='campaign_modifications')
    op.drop_index(op.f('ix_campaign_modifications_client_id'), table_name='campaign_modifications')
    op.drop_index(op.f('ix_campaign_modifications_analysis_id'), table_name='campaign_modifications')
    op.drop_index(op.f('ix_campaign_modifications_action_type'), table_name='campaign_modifications')
    op.drop_index('idx_modifications_status_client', table_name='campaign_modifications')
    op.drop_index('idx_modifications_priority', table_name='campaign_modifications')
    op.drop_table('campaign_modifications')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_resource_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_resource_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_ai_consensus_sessions_id'), table_name='ai_consensus_sessions')
    op.drop_index(op.f('ix_ai_consensus_sessions_analysis_id'), table_name='ai_consensus_sessions')
    op.drop_table('ai_consensus_sessions')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_ghl_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_client_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lsa_metrics_id'), table_name='lsa_metrics')
    op.drop_index(op.f('ix_lsa_metrics_date'), table_name='lsa_metrics')
    op.drop_index(op.f('ix_lsa_metrics_client_id'), table_name='lsa_metrics')
    op.drop_table('lsa_metrics')
    op.drop_index(op.f('ix_lsa_leads_status'), table_name='lsa_leads')
    op.drop_index(op.f('ix_lsa_leads_lead_id'), table_name='lsa_leads')
    op.drop_index(op.f('ix_lsa_leads_id'), table_name='lsa_leads')
    op.drop_index(op.f('ix_lsa_leads_client_id'), table_name='lsa_leads')
    op.drop_index(op.f('ix_lsa_leads_charged'), table_name='lsa_leads')
    op.drop_table('lsa_leads')
    op.drop_index(op.f('ix_google_ads_search_terms_search_term'), table_name='google_ads_search_terms')
    op.drop_index(op.f('ix_google_ads_search_terms_id'), table_name='google_ads_search_terms')
    op.drop_index(op.f('ix_google_ads_search_terms_date'), table_name='google_ads_search_terms')
    op.drop_index(op.f('ix_google_ads_search_terms_client_id'), table_name='google_ads_search_terms')
    op.drop_index('idx_search_terms_zero_conv', table_name='google_ads_search_terms')
    op.drop_index('idx_search_terms_search_term', table_name='google_ads_search_terms')
    op.drop_index('idx_search_terms_client_date', table_name='google_ads_search_terms')
    op.drop_table('google_ads_search_terms')
    op.drop_index(op.f('ix_google_ads_keywords_keyword_text'), table_name='google_ads_keywords')
    op.drop_index(op.f('ix_google_ads_keywords_keyword_id'), table_name='google_ads_keywords')
    op.drop_index(op.f('ix_google_ads_keywords_id'), table_name='google_ads_keywords')
    op.drop_index(op.f('ix_google_ads_keywords_date'), table_name='google_ads_keywords')
    op.drop_index(op.f('ix_google_ads_keywords_client_id'), table_name='google_ads_keywords')
    op.drop_index('idx_keywords_quality_score', table_name='google_ads_keywords')
    op.drop_index('idx_keywords_client_date', table_name='google_ads_keywords')
    op.drop_table('google_ads_keywords')
    op.drop_index(op.f('ix_google_ads_campaigns_id'), table_name='google_ads_campaigns')
    op.drop_index(op.f('ix_google_ads_campaigns_date'), table_name='google_ads_campaigns')
    op.drop_index(op.f('ix_google_ads_campaigns_client_id'), table_name='google_ads_campaigns')
    op.drop_index(op.f('ix_google_ads_campaigns_campaign_id'), table_name='google_ads_campaigns')
    op.drop_index('idx_campaigns_client_date', table_name='google_ads_campaigns')
    op.drop_index('idx_campaigns_campaign_id', table_name='google_ads_campaigns')
    op.drop_table('google_ads_campaigns')
    op.drop_index(op.f('ix_google_ads_ad_groups_id'), table_name='google_ads_ad_groups')
    op.drop_index(op.f('ix_google_ads_ad_groups_date'), table_name='google_ads_ad_groups')
    op.drop_index(op.f('ix_google_ads_ad_groups_client_id'), table_name='google_ads_ad_groups')
    op.drop_index(op.f('ix_google_ads_ad_groups_campaign_id'), table_name='google_ads_ad_groups')
    op.drop_index(op.f('ix_google_ads_ad_groups_ad_group_id'), table_name='google_ads_ad_groups')
    op.drop_index('idx_ad_groups_client_date', table_name='google_ads_ad_groups')
    op.drop_table('google_ads_ad_groups')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_client_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_clients_status'), table_name='clients')
    op.drop_index(op.f('ix_clients_slug'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_google_ads_customer_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_ghl_location_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_ghl_contact_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###

