"""Fix keyword unique constraint to include ad_group_id

Revision ID: e5cdde793268
Revises: ccad2446c1e9
Create Date: 2025-10-18 10:13:33.208947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5cdde793268'
down_revision = 'ccad2446c1e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_keyword_date'), 'google_ads_keywords', type_='unique')
    op.create_unique_constraint('uq_keyword_date', 'google_ads_keywords', ['client_id', 'ad_group_id', 'keyword_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_keyword_date', 'google_ads_keywords', type_='unique')
    op.create_unique_constraint(op.f('uq_keyword_date'), 'google_ads_keywords', ['client_id', 'keyword_id', 'date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###

